[package]
name = "pixlib_formats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-strings = "1"
lazy_static = "1.4"
nom = "7"
