[package]
name = "pixlib"
version = "0.1.0"
edition = "2021"

[dependencies]
cdfs = { path = "../iso9660-rs/cdfs" }
pixlib_formats = { git = "ssh://github.com/Dove6/piXlib-formats.git", rev = "a7ae7a58fcffefd39af40bc8dc9221ae4725bcbb" }
pixlib_parser = { path = "../pixlib_parser" }
codepage-strings = "1"
bevy = { version = "0.13", default_features = false, features = [
    "bevy_asset",
    "bevy_audio",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
    "multi-threaded",
    # "bevy_ci_testing",
    "bmp",
    # "file_watcher",
    "jpeg",
    "wav",
] }
regex = "1.10"
